import type { Conversation, CustomOrderRequest, Customer, Order, Product } from "@/lib/types";

export const products: Product[] = [
  { id: "prd-1", name: "Classic Biko", category: "Kakanin", price: 180, description: "Sticky rice cake topped with rich coconut latik.", tags: ["classic", "latik"], isBestSeller: true },
  { id: "prd-2", name: "Special Sapin-Sapin", category: "Kakanin", price: 220, description: "Layered rice delicacy with ube, langka, and coconut.", tags: ["ube", "party"], isBestSeller: true },
  { id: "prd-3", name: "Puto Bumbong", category: "Kakanin", price: 160, description: "Steamed purple rice served with sugar and coconut.", tags: ["seasonal"], isBestSeller: false },
  { id: "prd-4", name: "Suman sa Lihiya", category: "Suman", price: 120, description: "Chewy suman wrapped in banana leaves.", tags: ["native"], isBestSeller: false },
  { id: "prd-5", name: "Suman Moron", category: "Suman", price: 145, description: "Chocolate-vanilla twisted suman inspired by Leyte style.", tags: ["chocolate"], isBestSeller: true },
  { id: "prd-6", name: "Kutsinta", category: "Kakanin", price: 110, description: "Chewy kutsinta topped with fresh grated coconut.", tags: ["merienda"], isBestSeller: false },
  { id: "prd-7", name: "Party Tray Biko", category: "Party Trays", price: 980, description: "Large biko tray perfect for events and celebrations.", tags: ["bulk", "events"], isBestSeller: true },
  { id: "prd-8", name: "Cassava Cake", category: "Kakanin", price: 260, description: "Soft cassava cake with creamy custard topping.", tags: ["dessert"], isBestSeller: true },
];

export const orders: Order[] = [
  {
    id: "AAK-2001",
    customerName: "Maria Santos",
    customerPhone: "0917-123-4567",
    items: [
      { productId: "prd-1", name: "Classic Biko", qty: 2, price: 180, subtotal: 360 },
      { productId: "prd-6", name: "Kutsinta", qty: 1, price: 110, subtotal: 110 },
    ],
    total: 470,
    paymentMethod: "GCash",
    deliveryMode: "Delivery",
    deliveryAddress: "Blk 7 Lot 14, San Pedro, Laguna",
    status: "Pending",
    createdAt: "2026-02-26 08:15 AM",
  },
  {
    id: "AAK-2002",
    customerName: "John Carlo Reyes",
    customerPhone: "0922-334-9876",
    items: [{ productId: "prd-7", name: "Party Tray Biko", qty: 1, price: 980, subtotal: 980 }],
    total: 980,
    paymentMethod: "COD",
    deliveryMode: "Pick-up",
    status: "Preparing",
    createdAt: "2026-02-26 08:48 AM",
  },
  {
    id: "AAK-2003",
    customerName: "Aileen Dela Cruz",
    customerPhone: "0939-991-2201",
    items: [
      { productId: "prd-5", name: "Suman Moron", qty: 3, price: 145, subtotal: 435 },
      { productId: "prd-3", name: "Puto Bumbong", qty: 2, price: 160, subtotal: 320 },
    ],
    total: 755,
    paymentMethod: "GCash",
    deliveryMode: "Delivery",
    deliveryAddress: "Golden City Subdivision, Santa Rosa, Laguna",
    status: "Out for Delivery",
    createdAt: "2026-02-26 09:32 AM",
  },
  {
    id: "AAK-2004",
    customerName: "Ramon Villanueva",
    customerPhone: "0918-550-1122",
    items: [{ productId: "prd-8", name: "Cassava Cake", qty: 2, price: 260, subtotal: 520 }],
    total: 520,
    paymentMethod: "COD",
    deliveryMode: "Delivery",
    deliveryAddress: "Pulo, Cabuyao, Laguna",
    status: "Delivered",
    createdAt: "2026-02-25 04:12 PM",
  },
  {
    id: "AAK-2005",
    customerName: "Shiela Garcia",
    customerPhone: "0945-111-2233",
    items: [
      { productId: "prd-2", name: "Special Sapin-Sapin", qty: 1, price: 220, subtotal: 220 },
      { productId: "prd-4", name: "Suman sa Lihiya", qty: 2, price: 120, subtotal: 240 },
    ],
    total: 460,
    paymentMethod: "GCash",
    deliveryMode: "Pick-up",
    status: "Cancelled",
    createdAt: "2026-02-25 02:10 PM",
  },
  {
    id: "AAK-2006",
    customerName: "Patrick Lim",
    customerPhone: "0977-889-7700",
    items: [{ productId: "prd-1", name: "Classic Biko", qty: 1, price: 180, subtotal: 180 }],
    total: 180,
    paymentMethod: "GCash",
    deliveryMode: "Delivery",
    deliveryAddress: "Southville 3, Muntinlupa",
    status: "Pending",
    createdAt: "2026-02-26 10:20 AM",
  },
  {
    id: "AAK-2007",
    customerName: "Leah Mendoza",
    customerPhone: "0916-008-7744",
    items: [
      { productId: "prd-7", name: "Party Tray Biko", qty: 1, price: 980, subtotal: 980 },
      { productId: "prd-8", name: "Cassava Cake", qty: 1, price: 260, subtotal: 260 },
    ],
    total: 1240,
    paymentMethod: "COD",
    deliveryMode: "Delivery",
    deliveryAddress: "Binan Central, Laguna",
    status: "Preparing",
    createdAt: "2026-02-26 07:55 AM",
  },
  {
    id: "AAK-2008",
    customerName: "Jerome Bautista",
    customerPhone: "0928-100-3300",
    items: [{ productId: "prd-6", name: "Kutsinta", qty: 4, price: 110, subtotal: 440 }],
    total: 440,
    paymentMethod: "GCash",
    deliveryMode: "Pick-up",
    status: "Delivered",
    createdAt: "2026-02-24 03:00 PM",
  },
];

export const customers: Customer[] = [
  { id: "cus-1", name: "Maria Santos", phone: "0917-123-4567", email: "maria.santos@gmail.com", totalOrders: 9, totalSpent: 4860, lastOrderDate: "2026-02-26", status: "Active" },
  { id: "cus-2", name: "John Carlo Reyes", phone: "0922-334-9876", email: "jcreyes@yahoo.com", totalOrders: 5, totalSpent: 3540, lastOrderDate: "2026-02-26", status: "Active" },
  { id: "cus-3", name: "Aileen Dela Cruz", phone: "0939-991-2201", email: "aileen.dc@gmail.com", totalOrders: 4, totalSpent: 2780, lastOrderDate: "2026-02-26", status: "Active" },
  { id: "cus-4", name: "Ramon Villanueva", phone: "0918-550-1122", email: "ramon.villanueva@outlook.com", totalOrders: 7, totalSpent: 5220, lastOrderDate: "2026-02-25", status: "Active" },
  { id: "cus-5", name: "Shiela Garcia", phone: "0945-111-2233", email: "shiela.garcia@gmail.com", totalOrders: 2, totalSpent: 920, lastOrderDate: "2026-02-25", status: "Inactive" },
  { id: "cus-6", name: "Patrick Lim", phone: "0977-889-7700", email: "patrick.lim@gmail.com", totalOrders: 3, totalSpent: 1360, lastOrderDate: "2026-02-26", status: "Active" },
  { id: "cus-7", name: "Leah Mendoza", phone: "0916-008-7744", email: "leahmendoza@gmail.com", totalOrders: 6, totalSpent: 6940, lastOrderDate: "2026-02-26", status: "Active" },
  { id: "cus-8", name: "Jerome Bautista", phone: "0928-100-3300", email: "jbautista@gmail.com", totalOrders: 1, totalSpent: 440, lastOrderDate: "2026-02-24", status: "Inactive" },
];

export const conversations: Conversation[] = [
  {
    id: "conv-1",
    customer: { id: "cus-1", name: "Maria Santos", phone: "0917-123-4567" },
    status: "open",
    unreadCount: 2,
    messages: [
      { id: "msg-1", role: "customer", content: "Hi po, what time ang delivery ng order ko?", timestamp: "08:40 AM" },
      { id: "msg-2", role: "admin", content: "Nasa queue na po, within 1 hour po expected arrival.", timestamp: "08:43 AM" },
      { id: "msg-3", role: "customer", content: "Pwede po add extra latik?", timestamp: "08:44 AM" },
    ],
  },
  {
    id: "conv-2",
    customer: { id: "cus-4", name: "Ramon Villanueva", phone: "0918-550-1122" },
    status: "resolved",
    unreadCount: 0,
    messages: [
      { id: "msg-4", role: "customer", content: "Received na po, thank you sa mabilis na delivery.", timestamp: "Yesterday 05:10 PM" },
      { id: "msg-5", role: "admin", content: "Salamat po, happy to serve!", timestamp: "Yesterday 05:12 PM" },
      { id: "msg-6", role: "customer", content: "Order ulit kami next week.", timestamp: "Yesterday 05:15 PM" },
    ],
  },
  {
    id: "conv-3",
    customer: { id: "cus-2", name: "John Carlo Reyes", phone: "0922-334-9876" },
    status: "open",
    unreadCount: 1,
    messages: [
      { id: "msg-7", role: "customer", content: "Open po ba kayo Sunday for pickup?", timestamp: "07:20 AM" },
      { id: "msg-8", role: "admin", content: "Yes po, open kami 7AM to 6PM.", timestamp: "07:25 AM" },
      { id: "msg-9", role: "customer", content: "Sige po, order ako mamaya.", timestamp: "07:26 AM" },
    ],
  },
  {
    id: "conv-4",
    customer: { id: "cus-7", name: "Leah Mendoza", phone: "0916-008-7744" },
    status: "open",
    unreadCount: 3,
    messages: [
      { id: "msg-10", role: "customer", content: "Nag error po GCash, pwede COD na lang?", timestamp: "09:11 AM" },
      { id: "msg-11", role: "customer", content: "Order AAK-2007 po", timestamp: "09:12 AM" },
      { id: "msg-12", role: "admin", content: "Noted po, i-update ko payment to COD.", timestamp: "09:14 AM" },
    ],
  },
  {
    id: "conv-5",
    customer: { id: "cus-3", name: "Aileen Dela Cruz", phone: "0939-991-2201" },
    status: "open",
    unreadCount: 0,
    messages: [
      { id: "msg-13", role: "customer", content: "May low sugar option po ba for cassava cake?", timestamp: "Yesterday 10:04 AM" },
      { id: "msg-14", role: "admin", content: "Meron po by request, 1 day advance notice lang.", timestamp: "Yesterday 10:12 AM" },
      { id: "msg-15", role: "customer", content: "Great, pa reserve po for Friday.", timestamp: "Yesterday 10:14 AM" },
    ],
  },
];

export const customOrderRequests: CustomOrderRequest[] = [
  {
    id: "cor-1",
    customer: { id: "cus-9", name: "Grace Lim", phone: "0919-200-4455" },
    status: "Pending Review",
    messages: [
      { id: "cor-msg-1", role: "customer", content: "Need 6 party trays of biko for barangay event this Saturday.", timestamp: "08:00 AM" },
      { id: "cor-msg-2", role: "admin", content: "Checking slot and final pricing for bulk order.", timestamp: "08:10 AM" },
      { id: "cor-msg-3", role: "customer", content: "Can include dedication card per tray?", timestamp: "08:12 AM" },
    ],
  },
  {
    id: "cor-2",
    customer: { id: "cus-10", name: "Ken Castaneda", phone: "0920-332-1188" },
    status: "Quoted",
    agreedPrice: 3200,
    description: "Custom ube leche flan sapin-sapin for 40 pax",
    quantity: 40,
    deliveryDate: "2026-03-05",
    messages: [
      { id: "cor-msg-4", role: "customer", content: "Pwede custom ube leche flan sapin-sapin for 40 pax?", timestamp: "Yesterday 03:00 PM" },
      { id: "cor-msg-5", role: "admin", content: "Yes po. Initial quote is PHP 3,200 including packaging.", timestamp: "Yesterday 03:20 PM" },
      { id: "cor-msg-6", role: "customer", content: "Please reserve po for next Friday.", timestamp: "Yesterday 03:22 PM" },
    ],
  },
  {
    id: "cor-3",
    customer: { id: "cus-11", name: "Mica Javier", phone: "0933-445-9011" },
    status: "Confirmed",
    agreedPrice: 4500,
    description: "Mixed party trays for birthday with pink theme labels",
    quantity: 5,
    deliveryDate: "2026-03-08",
    messages: [
      { id: "cor-msg-7", role: "customer", content: "Need mixed party trays for 18th birthday, pink theme.", timestamp: "10:05 AM" },
      { id: "cor-msg-8", role: "admin", content: "Confirmed po, we can add pink labels and ribbons.", timestamp: "10:20 AM" },
      { id: "cor-msg-9", role: "customer", content: "Great, please proceed.", timestamp: "10:21 AM" },
    ],
  },
];
